import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from './Header.module.scss';
import menuList from '../../static/menuList.json';
import classNames from 'classnames';

export default function Header() {
  const [showMenu, setShowMenu] = useState(false);

  return (
    <header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.headerInner}>
          <div className={styles.logoSearchWrap}>
            <div className={styles.logo}>
              <Image
                src={'/images/header/logo.png'}
                alt="Logo"
                width={90}
                height={45}
                layout="responsive"
              />
            </div>

            <div className={styles.search}>
              <div className={styles.searchImage}>
                <Image
                  src={'/images/header/search.png'}
                  alt="search"
                  width={18}
                  height={18}
                  layout="responsive"
                />
              </div>
              <input placeholder="Search store" />
            </div>
          </div>
          <div className={styles.menuWrap}>
            <div className={styles.mainMenuButtonWrap}>
              <button
                onClick={() => setShowMenu(!showMenu)}
                className={classNames(styles.menuButton, {
                  [styles.menuButtonActive]: showMenu,
                })}
              >
                <span>Menu</span>
              </button>
              <div
                className={classNames(styles.mainMenuWrap, {
                  [styles.mainMenuWrapActive]: showMenu,
                })}
              >
                <ul className={styles.mainMenu}>
                  {menuList.map((item, index) => {
                    return (
                      <li key={index}>
                        <Link href={item.link}>
                          <a>{item.name}</a>
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </div>
            <div className={styles.userMenu}>
              <button className={styles.userButton}>
                <Image
                  src={'/images/mainContent/unlike.png'}
                  alt="basket"
                  width={20}
                  height={20}
                  layout="fixed"
                />
              </button>
              <button className={styles.userButton}>
                <Image
                  src={'/images/header/basket.png'}
                  alt="basket"
                  width={24}
                  height={24}
                  layout="fixed"
                />
              </button>
              <button className={styles.userButton}>
                <Image
                  src={'/images/header/person.png'}
                  alt="person"
                  width={24}
                  height={24}
                  layout="fixed"
                />
              </button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
